// Generated by https://quicktype.io

export default interface DailyMenuList {
    daily_menu: DailyMenu[];
}

export interface DailyMenu {
    daily_menu_id: string;
    name:          string;
    start_date:    string;
    end_date:      string;
    dishes:        Dish[];
}

export interface Dish {
    dish_id: string;
    name:    string;
    price:   string;
}
